
# Social [Change]{.change} Workshop 06/05/23 {.r-fit-text}

Are you passionate about social change and a more sustainable future? Do you want to connect with like-minded people and researchers in the Lund region? Join us for a one-day workshop on May 6th, 2023 at the Auditorium SOL!

Our aim is to create a space for collaboration, exchange, and experimentation. We want to hear from you, the activists and changemakers, about your experiences and ideas for creating a more sustainable future. Creating change in society is difficult and challenging, and we do not have all the answers. But we believe that we can learn from each other and find useful ideas, tools and inspiration in each of our experiences and backgrounds.

Throughout the day, we will have various sessions where researchers will share their insights and facilitate discussions on different aspects of change. But don't worry, we aim to keep the sessions broad and accessible to everyone. This can mean short talks followed by discussions, hands-on activities like crafting messages and strategies, or exploring example cases.

We welcome up to 50 participants from social activist groups, universities, and the general public. Let's build bridges between researchers and activists, and be inspired by each other to create a more sustainable future!

Below you can find more information about the workshop, including the agenda, speakers, and how to register.
If this already sounds like something you just do not want to miss, you can directly jump to the [registration form](#sign-up).
The **last day to sign up is the 18th of April**.

## Agenda

| Start | End   | Session                                                                | With                       |
|-------|-------|------------------------------------------------------------------------|----------------------------|
| 9:00  | 9:15  | Arrival & Check In                                                     |                            |
| 9:15  | 10:00 | Keynote                                                                | TBA                        |
| 10:00 | 10:45 | Fish Bowl Discussion                                                   | NGO, Scientist, You        |
| 10:45 | 11:00 | Break                                                                  |                            |
| 11:00 | 11:45 | Pro-environmental values: how to mold them into changing our behaviour | Georgeis Tsiakiris         |
| 11:45 | 12:30 | Violence in protest communication                                      | Cheryl Fung                |
| 12:30 | 13:30 | Lunch                                                                  | -                          |
| 13:30 | 14:15 | TBA                                                                    | Barbara Magalhaes Teixeira |
| 14:15 | 15:00 | Strategies and tactics of convergence for climate justice              | Salvatore Paolo De Rosa    |
| 15:15 | 15:30 | Wrap-up                                                                | -                          |

## Location

The workshop will take place at the Auditorium SOL, located at the University of Lund. The address is *Finngatan 1, 223 62 Lund*. 
You can find more information about the premise [here](https://www.kom.lu.se/en/sol-buildings/premises/).


## Food

For lunch, we will provide a vegetarian lunch. If you have any dietary restrictions, please let us know in the registration form.

## Sign Up

<div class="container">
<iframe class="responsive-iframe" src="https://forms.office.com/e/DeKP7hSdGK?embed=true"> </iframe>
</div>

## Contact

If you have any questions, please contact [Philipp Jonas Kreutzer](pjkreutzer.github.io) by sending an email to [philipp_jonas.kreutzer@ekh.lu.se](mailto:philipp_jonas.kreutzer@ekh.lu.se).